=== wilions/pycalphad/tdb-forge/schemas/assessment.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CalphadAssessment",
  "description": "Schema for extracted Calphad thermodynamic and mobility parameter assessments from literature",
  "type": "object",
  "properties": {
    "doi": { "type": "string" },
    "system": { "type": "string" },
    "elements": {
      "type": "array",
      "items": { "type": "string" }
    },
    "phases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "sublattices": {
            "type": "array",
            "items": { "type": "number" }
          },
          "constituents": {
            "type": "array",
            "items": {
              "type": "array",
              "items": { "type": "string" }
            }
          },
          "model_hints": {
            "type": "object",
            "properties": {
              "ordered_phase": { "type": "string" },
              "disordered_phase": { "type": "string" },
              "never_disorder": { "type": "boolean" },
              "ihj_magnetic_afm_factor": { "type": "number" },
              "ihj_magnetic_structure_factor": { "type": "number" },
              "symmetry_FCC_4SL": { "type": "boolean" },
              "symmetry_BCC_4SL": { "type": "boolean" },
              "ionic_liquid_2SL": { "type": "boolean" },
              "liquid": { "type": "boolean" },
              "gas": { "type": "boolean" }
            },
            "additionalProperties": false
          }
        },
        "required": ["name", "sublattices", "constituents"]
      }
    },
    "functions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "pieces": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "T_limits": {
                  "type": "array",
                  "items": { "type": "number" },
                  "minItems": 2,
                  "maxItems": 2
                },
                "expression": { "type": "string" }
              },
              "required": ["T_limits", "expression"]
            }
          }
        },
        "required": ["name", "pieces"]
      }
    },
    "parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "type": "string", "enum": ["G", "L", "TC", "BMAGN", "MQ"] },
          "phase": { "type": "string" },
          "constituent_array": {
            "type": "array",
            "items": {
              "type": "array",
              "items": { "type": "string" }
            }
          },
          "diffusing_species": { "type": "string" },
          "parameter_order": { "type": "integer" },
          "pieces": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "T_limits": {
                  "type": "array",
                  "items": { "type": "number" },
                  "minItems": 2,
                  "maxItems": 2
                },
                "expression": { "type": "string" }
              },
              "required": ["T_limits", "expression"]
            }
          },
          "reference_tag": { "type": "string" }
        },
        "required": ["type", "phase", "constituent_array", "parameter_order", "pieces"]
      }
    }
  },
  "required": ["doi", "elements", "phases", "functions", "parameters"]
}

=== wilions/pycalphad/tdb-forge/extracted/alzn_mey.json
{
  "doi": "10.1007/BF02661386",
  "system": "Al-Zn",
  "elements": ["AL", "ZN"],
  "phases": [
    {
      "name": "LIQUID",
      "sublattices": [1.0],
      "constituents": [["AL", "ZN"]]
    },
    {
      "name": "FCC_A1",
      "sublattices": [1.0],
      "constituents": [["AL", "ZN"]]
    },
    {
      "name": "HCP_A3",
      "sublattices": [1.0],
      "constituents": [["AL", "ZN"]]
    }
  ],
  "functions": [
    {
      "name": "GALLIQ",
      "pieces": [
        {
          "T_limits": [298.0, 700.0],
          "expression": "+3029.403+125.2307*T-24.36720*T*LN(T)-1.884662E-3*T**2-0.877664E-6*T**3+74092*T**(-1)+79.401E-21*T**7"
        },
        {
          "T_limits": [700.0, 933.6],
          "expression": "-270.6860+211.1861*T-38.58443*T*LN(T)+18.53198E-3*T**2-5.764227E-6*T**3+74092*T**(-1)+79.401E-21*T**7"
        },
        {
          "T_limits": [933.6, 2900.0],
          "expression": "-795.7090+177.4100*T-31.74819*T*LN(T)"
        }
      ]
    },
    {
      "name": "GALHCP",
      "pieces": [
        {
          "T_limits": [298.0, 6000.0],
          "expression": "+5481-1.8*T+GHSERAL#"
        }
      ]
    },
    {
      "name": "GZNLIQ",
      "pieces": [
        {
          "T_limits": [298.14, 692.7],
          "expression": "+7157.213-10.29299*T-3.5896E-19*T**7+GHSERZN#"
        },
        {
          "T_limits": [692.7, 1700.0],
          "expression": "+7450.168-10.737066*T-4.7051E+26*T**(-9)+GHSERZN#"
        }
      ]
    },
    {
      "name": "GZNFCC",
      "pieces": [
        {
          "T_limits": [298.15, 1700.0],
          "expression": "+2969.82-1.56968*T+GHSERZN#"
        }
      ]
    }
  ],
  "parameters": [
    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["AL"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 2900.0],
          "expression": "+GALLIQ#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 1700.0],
          "expression": "+GZNLIQ#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "+10465.5-3.39259*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 2900.0],
          "expression": "+GHSERAL#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 1700.0],
          "expression": "+GZNFCC#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "+7297.5+0.47512*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 1,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "+6612.9-4.5911*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 2,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-3097.2+3.30635*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "HCP_A3",
      "constituent_array": [["AL"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 2900.0],
          "expression": "+GALHCP#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "HCP_A3",
      "constituent_array": [["ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 1700.0],
          "expression": "+GHSERZN#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "HCP_A3",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "+18821.0-8.95255*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "HCP_A3",
      "constituent_array": [["AL", "ZN"]],
      "parameter_order": 3,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-702.8"
        }
      ]
    }
  ]
}

=== wilions/pycalphad/tdb-forge/extracted/alsc_thermo.json
{
  "doi": "10.1007/s11669-008-9366-z",
  "system": "Al-Sc",
  "elements": ["AL", "SC"],
  "phases": [
    {
      "name": "LIQUID",
      "sublattices": [1.0],
      "constituents": [["AL", "SC"]]
    },
    {
      "name": "FCC_A1",
      "sublattices": [1.0],
      "constituents": [["AL", "SC"]]
    },
    {
      "name": "AL3SC",
      "sublattices": [0.75, 0.25],
      "constituents": [["AL"], ["SC"]]
    }
  ],
  "functions": [

    {
      "name": "GSCLIQ",
      "pieces": [
        {
          "T_limits": [298.15, 1608.0],
          "expression": "+14111.4-7.5645*T+GHSERSC#"
        },
        {
          "T_limits": [1608.0, 3000.0],
          "expression": "+18822.2-10.4908*T+GHSERSC#"
        }
      ]
    }
  ],
  "parameters": [

    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["SC"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "+GSCLIQ#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["AL", "SC"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-85000+10.0*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "LIQUID",
      "constituent_array": [["AL", "SC"]],
      "parameter_order": 1,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-15000"
        }
      ]
    },

    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["SC"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "+GHSERSC#"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL", "SC"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-78000+12.0*T"
        }
      ]
    },
    {
      "type": "G",
      "phase": "FCC_A1",
      "constituent_array": [["AL", "SC"]],
      "parameter_order": 1,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-10000"
        }
      ]
    },
    {
      "type": "G",
      "phase": "AL3SC",
      "constituent_array": [["AL"], ["SC"]],
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 6000.0],
          "expression": "-43500+5.5*T+0.75*GHSERAL#+0.25*GHSERSC#"
        }
      ]
    }
  ]
}

=== wilions/pycalphad/tdb-forge/extracted/al_impurity_mobility.json
{
  "doi": "10.1016/S0964-1807(03)00084-2",
  "system": "Al-Mg-Si-Sc-Zr-Fe-mobility",
  "elements": ["AL", "MG", "SI", "SC", "ZR", "FE"],
  "phases": [
    {
      "name": "FCC_A1",
      "sublattices": [1.0, 1.0],
      "constituents": [["AL", "MG", "SI", "SC", "ZR", "FE"], ["VA"]]
    }
  ],
  "functions": [],
  "parameters": [
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "AL",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-142000 + 8.31451 * T * LN(1.47E-4)"
        }
      ]
    },
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "MG",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-120500 + 8.31451 * T * LN(1.49E-4)"
        }
      ]
    },
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "SI",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-124000 + 8.31451 * T * LN(2.02E-4)"
        }
      ]
    },
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "SC",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-173000 + 8.31451 * T * LN(5.31E-4)"
        }
      ]
    },
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "ZR",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-242000 + 8.31451 * T * LN(7.28E-4)"
        }
      ]
    },
    {
      "type": "MQ",
      "phase": "FCC_A1",
      "constituent_array": [["AL"], ["VA"]],
      "diffusing_species": "FE",
      "parameter_order": 0,
      "pieces": [
        {
          "T_limits": [298.15, 3000.0],
          "expression": "-220000 + 8.31451 * T * LN(3.32E-2)"
        }
      ]
    }
  ]
}
